Algoritmo "repita"

Var
// Seção de Declarações das variáveis 
   opcao: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
      repita
            escreval("Escolha uma opção:")
            escreval("1- Cadastrar")
            escreval("2- Listar")
            escreval("0- sair")
            leia(opcao)
      ate opcao = 0
      
      escreval("Programa encerrado")

Fimalgoritmo