Algoritmo "meuPrimeiroAlgoritmo"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Alauana Jackeline
// Descrição   : Apresentação
// Autor(a)    : Laura
// Data atual  : 28/01/2026
Var
// Seção de Declarações das variáveis 
   nome: caractere
   idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
      escreval("Qual seu nome? ")
      leia(nome)
      escreval("Olá, ", nome, "!")

Fimalgoritmo